language: node_js
node_js:
- "0.12"
before_install:
- "npm install grunt-cli"
- "npm install grunt"
- "npm install grunt-jasmine-node"
- "echo \"module.exports=function(grunt){grunt.initConfig({jasmine:{src:'js/**/*.js',options:{specs:'spec/**/*.js'}}});grunt.loadNpmTasks('grunt-jasmine-node');grunt.registerTask('default',['jasmine_node']);};\" > Gruntfile.js"
script:
- "grunt"
